---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: auth-deployment
 namespace: staging
 labels:
   app: auth-deploy
spec:
  replicas: 1
  template:
    metadata:
      name: auth-pod-template
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: 986381756175.dkr.ecr.us-east-1.amazonaws.com/labsoft-2018/auth:latest
          imagePullPolicy: Always
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: aws_secret_access_key
          - name: AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: aws_access_key_id
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: aws_secret_access_key
