#!/usr/bin/env bash
set -e

NAME="k8s-cluster.labsoft.host"
KOPS_STATE_STORE="s3://labsoft-host-cluster"
AWS_REGION_KOPS=us-east-1a
SSH_PATH="~/.ssh/k8s_labsoft.pub"
MININUM_NODE_COUNT=1
MININUM_MASTER_COUNT=1
MININUM_NODE_SIZE=t2.micro
MININUM_MASTER_SIZE=t2.micro
for arg in "$@"
do
    if [[ "$arg" == "down" ]]; then
      echo "Cluster is going down..."
      kops delete cluster k8s-cluster.labsoft.host --yes 
      echo "Success!"
    elif [[ "$arg" == "up" ]]; then
      echo "Calculating resources..."
      kops create cluster $NAME --cloud aws \
                          --ssh-public-key $SSH_PATH \
                          --zones $AWS_REGION_KOPS \
                          --node-count $MININUM_NODE_COUNT \
                          --master-count $MININUM_MASTER_COUNT \
                          --master-size $MININUM_MASTER_SIZE \
                          --node-size $MININUM_NODE_SIZE
      echo "Creating rescources..."
      kops update cluster $NAME --yes
      echo "Success!"
    elif [[ "$arg" == "up-prod" ]]; then
      echo "Not yet, buddy."
    else
        echo "Choose one of the following options:"
        echo "up -> create your cluster with minimal usage"
        echo "up-prod -> time to shine"
        echo "down -> deletes your cluster"
    fi
done
